# Generated by Django 2.2.28 on 2022-10-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0017_missing_migration_18-08-2022_hbrs'),
        ('checker', '0017_checkerresult_passed_with_warning'),
    ]

    operations = [
    ]

