# Generated by Django 2.2.28 on 2023-01-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0018_merge_20221012_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptchecker',
            name='arguments',
            field=models.CharField(blank=True, help_text='Additional arguments to pass to the script. Shell-like escaping and quoting is supported.', max_length=5000),
        ),
    ]
