# Generated by Django 5.2.14 on 2026-05-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0020_textchecker_begin_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptchecker',
            name='mount_extra_directories',
            field=models.BooleanField(default=False, help_text='Mount configured external extra directories into the checker Docker container.', verbose_name='Mount extra directories'),
        ),
    ]
