# Generated by Django 2.2.28 on 2022-12-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_max_file_size'),
        ('tasks', '0010_missing_migration_18-08-2022_hbrs'),
    ]

    operations = [
    ]
