# Generated by Django 2.2.28 on 2023-01-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accept_disclaimer'),
        ('tasks', '0011_merge_20221222_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The time up until the user has time to complete the task. This time will be extended by the duration configured with the deadline tolerance setting in case the student just missed the extended deadline.')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'User'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
