# Generated by Django 2.2.28 on 2023-09-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_deadlineextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='supported_file_types',
        ),
    ]
