# Generated by Django 2.2.28 on 2023-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_task_supported_file_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hide_solutions_of_expired_tasks',
            field=models.BooleanField(default=False, help_text='If enabled, solutions (incl. attestations) of expired tasks are not accessible for students while this task is accepting submissions.'),
        ),
    ]
