# Generated by Django 2.2.28 on 2024-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20240423_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exam',
            field=models.BooleanField(default=False, help_text="If enabled, solutions (incl. attestations) of expired tasks and active tasks that are not exams are not accessible for students starting 60 minutes before the publication date until 15 minutes after the deadline. Media files will only be visible while the task is active. After the deadline passed, solutions for this task won't be visible until they got attested."),
        ),
    ]
