# Generated by Django 2.2.28 on 2024-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20240510_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A short description of this file', max_length=255),
        ),
    ]
