# Generated by Django 2.2.28 on 2024-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_mediafile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_id',
            field=models.CharField(blank=True, help_text='The custom ID of the task that is available as an environment variable within a checker (TASK_ID_CUSTOM). This is also used to replace the task ID in the external directory path for the checkers.', max_length=255),
        ),
    ]
