# Generated by Django 2.2.28 on 2023-01-11 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_missing_migration_18-08-2022_hbrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='deadline_tolerance',
            field=models.DurationField(default=datetime.timedelta(0), help_text='The duration by which the submission date for a task will be extended for those who just missed the deadline.'),
        ),
    ]
