# Generated by Django 2.2.28 on 2024-04-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_auto_20230111_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='hide_solutions_of_expired_tasks',
        ),
    ]
