# Generated by Django 2.2.28 on 2023-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_remove_tar_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='all_checker_finished',
            field=models.BooleanField(default=False, help_text='Indicates whether all checkers have been run for this solution.'),
        ),
    ]
