# Generated by Django 5.2.14 on 2026-06-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_solution_all_checker_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='allow_llm_upload',
            field=models.BooleanField(default=False, help_text='Indicates whether the student allows the solution to be uploaded to an LLM.', verbose_name='I agree to my solution being uploaded to an LLM for evaluation purposes.'),
        ),
    ]
